colors = [
    "Pink",
    "Crimson",
    "Red",
    "Maroon",
    "Brown",
    "Misty",
    "Rose",
    "Salmon",
    "Coral",
    "Orange - Red",
    "Chocolate",
    "Orange",
    "Gold",
    "Ivory",
    "Yellow",
    "Olive",
    "Yellow - Green",
    "Lawn",
    "green",
    "Chartreuse",
    "Lime",
    "Green",
    "Aquamarine",
    "Turquoise",
    "Azure",
    "Aqua / Cyan",
    "Teal",
    "Lavender",
    "Blue",
    "Navy",
    "Blue - Violet",
    "Indigo",
    "Violet",
    "Plum",
    "Magenta",
    "Purple",
    "Red - Violet",
    "Tan",
    "Beige",
    "Gray",
    "White",
    "Silver", 'pink',
    'crimson',
    'red',
    'maroon',
    'brown',
    'misty',
    'rose',
    'salmon',
    'coral',
    'orange - red',
    'chocolate',
    'orange',
    'gold',
    'ivory',
    'yellow',
    'olive',
    'yellow - green',
    'lawn',
    'green',
    'chartreuse',
    'lime',
    'green',
    'aquamarine',
    'turquoise',
    'azure',
    'aqua / cyan',
    'teal',
    'lavender',
    'blue',
    'navy',
    'blue - violet',
    'indigo',
    'violet',
    'plum',
    'magenta',
    'purple',
    'red - violet',
    'tan',
    'beige',
    'gray',
    'white',
    'silver']
